name: dl-repo
channels:
  - anaconda
dependencies:
  - python>=3.6
  - anaconda
  - numpy>=1.16.2
  - scipy>=1.2.1
  - sphinx=>1.8.4
  - pytorch::pytorch>=1.2.0
  - pytorch::torchvision>=0.3.0
  - scikit-image=>0.14.2
  - pytorch::torchvision
  - cudatoolkit>=9.0
