name: dl-repo
channels:
  - conda-forge
  - anaconda
dependencies:
  - python>=3.6
  - anaconda
  - numpy>=1.16.2
  - scipy>=1.2.1
  - sphinx=>1.8.4
  - pytorch::pytorch>=1.0.1
  - pytorch::torchvision>=0.3.0
  - scikit-image=>0.14.2
  - fastai::fastai
  - pytorch::torchvision
  - cudatoolkit=9.0
  - pip
  - pip:
    - dvc[gs]
    - nevergrad
    - tensorboardX 
